---
title: "Forecasting"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r message=FALSE, warning=FALSE}
library(quantmod)
library(caret)
library(forecast)
library(dplyr)
library(ggplot2)
```

## Collect Data

```{r}
from.dat <- as.Date("01/01/08", format = "%m/%d/%y")
to.dat <- as.Date("12/31/13", format = "%m/%d/%y")
getSymbols("GOOG", src = "yahoo", from = from.dat, to = to.dat)
```

## EDA

```{r}
monthGoog <- to.monthly(GOOG)
googOpen <- Op(monthGoog)
ts1 <- ts(googOpen, frequency = 12)
plot(ts1, xlab = "Years + 1", ylab = "GOOG")
```


```{r}
plot(decompose(ts1), xlab = "Years + 1")
```

## Subsets

```{r}
ts1Train <- window(ts1, start = 1, end = 5)
ts1Test <- window(ts1, start = 5, end = (7 - 0.01))
ts1Train
```

## Moving Average

```{r}
plot(ts1Train)
lines(ma(ts1Train, order = 3), col = "red")
```

## Exponential Smoothing

```{r}
ets1 <- ets(ts1Train, model = "MMM")
fcast <- forecast(ets1)
plot(fcast)
lines(ts1Test, col = "red")
```

## Get Model Accuracy

```{r}
accuracy(fcast, ts1Test)
```

