---
title: "Multiple Covariates Linear Regression"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r}
library(ISLR)
library(caret)
library(ggplot2)
data(Wage)

Wage <- subset(Wage, select = -c(logwage))

summary(Wage)
```

## Subsets


```{r}
inTrain <- createDataPartition(y = Wage$wage, p = 0.7, list = FALSE)
training <- Wage[inTrain,]
testing <- Wage[-inTrain,]

dim(training)
dim(testing)
```

## EDA

### Feature Plot

```{r}
featurePlot(
    x = training[, c("age", "education", "jobclass")], 
    y = training$wage, 
    plot = "pairs"
)
```

### Quick Plots

```{r}
qplot(age, wage, color = jobclass, data = training)
```

```{r}
qplot(age, wage, color = education, data = training)
```

```{r message=FALSE, warning=FALSE}
modFit <- train(wage ~ age + jobclass + education, method = "lm", data = training)

print(modFit)
```

```{r}
finMod <- modFit$finalModel

plot(finMod, 1, pch = 19, cex = 0.5, col="#00000010")
```

## Plot Fitted Model x Residuals to preview Trends

Color by variables not used in the model

```{r}
qplot(finMod$fitted, finMod$residuals, color = race, data = training)
```

### Plot by Index

```{r}
plot(finMod$residuals, pch = 19)
```

## Predicted x Truth in Test Set

Obs: This is not to be used during training!! (it's a post-test analysis)

```{r}
pred <- predict(modFit, testing)
qplot(wage, pred, color = year, data = testing)
```

## Trying to use all Covariates

```{r message=FALSE, warning=FALSE}
modFitAll <- train(wage ~ ., data = training, method = "lm")
pred <- predict(modFitAll, testing)
qplot(wage, pred, data = testing)
```

