---
title: "Predicting with Regression"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r}
library(caret)
data("faithful")
```

## Separate Train and Test sets

```{r}
inTrain <- createDataPartition(y = faithful$waiting, p = 0.5, list = FALSE)
trainFaith <- faithful[inTrain,]
testFaith <- faithful[-inTrain,]
head(trainFaith)
```

## EDA

```{r}
plot(trainFaith$waiting, trainFaith$eruptions, pch = 19, col = "blue", xlab = "Waiting", ylab = "Duration")
```

## Fit a Linear Model

```{r}
lm1 <- lm(eruptions ~ waiting, data = trainFaith)
summary(lm1)$coef
```

```{r}
with(trainFaith, plot(waiting, eruptions, pch = 19, col = "blue", xlab = "Waiting", ylab = "Duration"))
lines(trainFaith$waiting, lm1$fitted, lwd = 3)

```

## Predict a New Value

Simulation of the prediction using lm coefficients

```{r}
# Y = b0 + b1 * X
coef(lm1)[1] + coef(lm1)[2] * 80
```

Actual prediction value

```{r}
newdata <- data.frame(waiting = 80)
predict(lm1, newdata)
```

## Plotting the prediction of training and test sets

```{r}
par(mfrow = c(1, 2))
plotVals <- function(df){with(df, plot(waiting, eruptions, pch = 19, col = "blue", xlab = "Waiting", ylab = "Duration"))}
plotVals(trainFaith)
lines(trainFaith$waiting, predict(lm1), lwd = 3)
plotVals(testFaith)
lines(testFaith$waiting, predict(lm1, newdata = testFaith), lwd = 3)
```

## Get training and test set Errors

### RMSE on Training

```{r}
sqrt(sum((lm1$fitted - trainFaith$eruptions)^2))
```

### RMSE on Testing

```{r}
sqrt(sum((predict(lm1, newdata = testFaith) - testFaith$eruptions)^2))
```

## Prediction Intervals

```{r}
pred1 <- predict(lm1, newdata = testFaith, interval = "prediction")
ord <- order(testFaith$waiting)

plot(testFaith$waiting, testFaith$eruptions, pch = 19, col = "blue")
matlines(testFaith$waiting[ord], pred1[ord,], type = "l", col = c(1, 2, 2), lty = c(1, 1, 1), lwd = 3)
```

## Fit model using CARET package

```{r}
modFit <- train(eruptions ~ waiting, data = trainFaith, method = "lm")
summary(modFit$finalModel)$coef
```
